base_locale: en
data:
  yaml:
    write:
      # do not wrap lines at 80 characters
      line_width: -1

# Find translate calls
search:
  paths:
    - 'app'
    - 'lib'

## Do not consider these keys missing:
ignore_missing:
  - 'activerecord*'
  - 'aria*'
  - 'date*'
  - 'number*'
  - 'views*'

ignore_unused:
  - 'spree.admin.webhooks_subscribers*'
  # - 'spree.admin.product*'
  - 'spree.admin.tab*'
