import './base'
import './api_routes'

import './animate_css'
import './fetch_request_utility'
import './ransack'
import './radio_panel_toggle'
import './responsive_menus'
import './select2_autocomplete'
import './select2_populate'
import './sortable'
import './side_scroll_indication'
import './select2'
