import './adjustments'
import './admin'
import './calculator'
import './gateway'
import './handlebar_extensions'
import './multi_currency'
import './option_value_picker'
import './product_picker'
import './progress'
import './promotions'
import './states'
import './stock_location'
import './stock_management'
// import './stock_movement'
// import './stock_transfer'
import './taxons'
import './user_picker'
import './zone'
